name: LLMApp

services:
  api:
    container_name: LLM_app_huggingface-api
    build:
      context: "./api"
      dockerfile: "Dockerfile"
      tags:
        - llmapp-api:latest
        - llmapp-api:${LATEST_COMMIT}
    volumes:
      - "./api:/api"
    ports:
      - "8000:5000"
    # attachable: true
    command:
      - "sleep infinity"
