name: LLMApp

services:
  api:
    container_name: LLM_app_huggingface-api
    build:
      context: "./api"
      dockerfile: "Dockerfile"
      tags:
        - llmapp-api:latest
        - llmapp-api:${LATEST_COMMIT}
    volumes:
      - "./api:/api"
    ports:
      - "8000:5000"
    command:
      - /bin/bash

    develop:
      watch:
        - action: sync
          path: "./api"
          target: "/api"
          ignore:
            - .venv/

  model:
    container_name: custom_llm_model
    build:
      context: ./RnD
      dockerfile: "Dockerfile"
      tags:
        - llm-model:production
    ports:
      - "8001:5001"
    command:
      - /bin/bash



