name: LLMApp

services:
  api:
    container_name: LLM_app_huggingface-api
    build:
      context: "./api"
      dockerfile: "Dockerfile_v1-1"
      secrets:
        - llm_arch
      tags:
        - llmapp-api:${VERSION}
      labels:
        - git.commit=${LATEST_COMMIT}
    volumes:
      - "./mlartifacts:/api/mlartifacts"
    command: ["uv", "run", "main.py"]

    develop:
      watch:
        - action: sync
          path: ./api
          target: /api
          ignore:
            - .venv/
            - Dockerfile_v0
            - access_tokens.env
            - .vscode/
            - .ipynb_checkpoints/
      # use `docker compose -f compose.yaml up api --watch` to build and run the container

secrets:
  llm_arch:
    environment: LLM_DOWNLOAD_ACCESS_TOKEN

