name: LLMApp

services:
  api:
    container_name: LLM_app_huggingface-api
    build:
      context: "./api"
      dockerfile: "Dockerfile_v1-1"
      secrets:
        - llm_arch
      tags:
        - llmapp-api:${VERSION}
      labels:
        - git.commit=${LATEST_COMMIT}
    volumes:
      - "./api:/api"
      - "./mlartifacts:/api/mlartifacts"
    # for developing inside a container, use volumes instead of watch for api.
    command: "sleep infinity"

secrets:
  llm_arch:
    environment: LLM_ARCH_DOWNLOAD_ACCESS_TOKEN

