
FROM python:3.12-slim-bookworm

RUN apt-get update && apt-get install -y --no-install-recommends curl ca-certificates make

# Install uv.
COPY --from=ghcr.io/astral-sh/uv:0.5.25 /uv /uvx /bin/

WORKDIR /RnD

COPY uv.lock uv.lock
COPY pyproject.toml pyproject.toml

RUN uv venv && uv sync

ENV PATH="/RnD/.venv/bin:$PATH"

COPY model.py model.py
COPY __init__.py __init__.py

ENTRYPOINT ["/bin/bash"]

CMD ["-c", "source .venv/bin/activate && python model.py"]

LABEL authors="sameervk"
