
# Use the official Python image from the Docker Hub
FROM python:3.12-slim-bookworm

RUN apt-get update && apt-get install -y --no-install-recommends curl ca-certificates make

# Install uv.
COPY --from=ghcr.io/astral-sh/uv:0.5.25 /uv /uvx /bin/

WORKDIR /api

COPY . .

# Sync the project: install dependencies
RUN uv sync --frozen --no-cache
# when not mounting the cache

# install RnD code
RUN --mount=type=secret,id=llm_arch,env=LLM_ARCH_DOWNLOAD_ACCESS_TOKEN\
    uv add https://{llm_arch}@raw.githubusercontent.com/sameervk/LLM_app_huggingface/main/dist/llmarch-0.0.1-py3-none-any.whl

# add this to the sys path
ENV PATH="/api/.venv/bin:$PATH"

LABEL authors="sameervk"

CMD ["uv", "run", "main.py"]