name: Deploy-To-HF

run-name: Build and test Gradio app and dependencies and deploy to HuggingFace Spaces


on:
  pull_request_target:
    branches:
      - main

  workflow_dispatch:

jobs:
  Build-and-Test:
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        shell: bash
        working-directory: ./GPT2_Arch_TestApp
    

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        # with:
        #   sparse-checkout: |
        #     GPT2_Arch_TestApp
          

      - name: Push to HF hub
        env:
          HF_TOKEN: ${{secrets.HF_ACCESS_TOKEN}}
        run: |
          git push https://skesava:$HF_TOKEN@huggingface.co/spaces/skesava/GPT2_Arch_TestApp main

# This is not working. The error message is 
# """
# To https://huggingface.co/spaces/skesava/GPT2_Arch_TestApp
#  ! [rejected]        main -> main (fetch first)
# error: failed to push some refs to 'https://huggingface.co/spaces/skesava/GPT2_Arch_TestApp'
# hint: Updates were rejected because the remote contains work that you do not
# hint: have locally. This is usually caused by another repository pushing to
# hint: the same ref. If you want to integrate the remote changes, use
# hint: 'git pull' before pushing again.
# hint: See the 'Note about fast-forwards' in 'git push --help' for details.
# """