name: Deploy-To-HF

run-name: Build and test Gradio app and dependencies and deploy to HuggingFace Spaces


on:
  pull_request_target:
    branches:
      - main

  workflow_dispatch:

jobs:
  Build-and-Test:
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        shell: bash
        working-directory: ./RnD
    

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            RnD
          

      steps:
            - name: Checkout code
              uses: actions/checkout@v2
    
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.12'
    
            - name: Install dependencies              
              run: |
                  curl -LsSf https://astral.sh/uv/0.5.25/install.sh | sh
                  uv sync --frozen --no-cache

            - name: Push model to HF Hub
              run: |
                  uv run hf_hub_push_model.py
# requires mlflow tracking server to execute this.
              