name: Deploy-To-HF

run-name: Build and test Gradio app and dependencies and deploy to HuggingFace Spaces


on:
  pull_request_target:
    branches:
      - main

  workflow_dispatch:

jobs:
  Build-and-Test:
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        shell: bash
        working-directory: ./GPT2_Arch_TestApp
    

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        # with:
        #   sparse-checkout: |
        #     GPT2_Arch_TestApp
          

      - name: Push to HF hub
        env:
          HF_TOKEN: ${{secrets.HF_ACCESS_TOKEN}}
        run: |
          git push https://skesava:$HF_TOKEN@huggingface.co/spaces/skesava/GPT2_Arch_TestApp main
