name: CI-Docker-UsingContainerService

run-name: Test docker container

on:
  pull_request_target:
    branches:
      - main

  workflow_dispatch:

jobs:
                  
    Container-Test:     
      runs-on: ubuntu-latest
      environment: production
      permissions:
        contents: read
      
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        
      container:        
        image: ghcr.io/sameervk/llm_app_huggingface:873b43b79f62f9a7dc6f53eae77fe35b67a4781a
        volumes:
          - ./mlartifacts:/api/mlartifacts
        
        # Add any other necessary volumes here
    
# Does not work because unable to upload mlartifacts to the repo.