name: CI-Docker-TestContainer

run-name: Test docker container

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
                  
    Container-Test:     
      runs-on: ubuntu-latest
      environment: production
      permissions:
        contents: read
      
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Docker Login
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Change repo to lowercase
          run: |
            echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
            echo "Changing repo name to lowercase": ${{ env.REPO }}

        - name: Test docker container
          run: |
            echo "Testing docker container"
            docker run --rm \
              -v ${{ github.workspace }}/mlartifacts:/api/mlartifacts \
              ghcr.io/sameervk/llm_app_huggingface:873b43b79f62f9a7dc6f53eae77fe35b67a4781a \
              /bin/bash -c "cd /api && make test"
        
        # Add any other necessary volumes here
    